### ISSUE TITLE
Update gambar profile bermasalah

### ISSUE THREAD

**Issue by yehezkielermanto** [yehezkielermanto/SecondHandFE#124]
mas @vitoradityafauzan mintol cekkan update gambar profile ya mas....waktu update gambar, gambarnya ndak mau keupdate

**Comment by vitorf-arc** [comment]
Di environment yg mna mas?

**Comment by yehezkielermanto** [comment]
di bagian FE waktu update profile mas...(update gambar baru), coba masnya jalankan edit profile di local dulu mas...soalnya aku ndak mau ke update gambarnya

**Comment by vitorf-arc** [comment]
udh ku benerin mas. trnyt di BE nya. udh ku push ke branch updateUser

**Comment by yehezkielermanto** [comment]
ok siap mas..langsung pull req ke staging terus ke master mas,

**Comment by yehezkielermanto** [comment]
sama lampirkan yang error di BE mas...
